sonar.organization=zackria
sonar.projectKey=zackria_bit-switch
sonar.projectName=Bit Switch

sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**

# LCOV coverage report produced by `flutter test --coverage`
sonar.dart.coverage.reportPaths=coverage/lcov.info
